<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="itext" Version="9.5.0" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Font_Times_New_Roman.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Font_Times_New_Roman.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Font_Times_New_Roman.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Font_Times_New_Roman.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\times.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
